site_name: 新疆大学 飞跃手册
site_description: 为有志同学提供保研辅导 + 学长经验分享平台
site_author: 计科院软开实验室

theme:
    name: material
    features:
        # - navigation.tabs
        - navigation.top
        - content.code.copy # Code Block Copy Button
    # ------ Dark and Light Mode ------
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to system preference
    # ------ Dark and Light Mode ------
repo_url: https://github.com/winbeau/mkdocs-wiki
markdown_extensions:
    - pymdownx.highlight: # Code Block
        linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite # Code Block
    - pymdownx.snippets # Code Block
    - pymdownx.superfences: # Mermaid
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex: # KaTeX
        generic: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_javascript:
  - assets/js/extra.js
  - assets/js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css
  - assets/css/extra.css

nav:
    - 首页: index.md
    - 关于我们: about.md
    - 历届经验:
      - 2025届经验:
        - 总体: experiences/2025/main.md
        - 郭子腾(UCAS): experiences/2025/郭子腾.md
        - 孙海洋(ZJU): experiences/2025/孙海洋.md
        - 夏清伟(BIT): experiences/2025/夏清伟.md
        - 严从营(USTC): experiences/2025/严从营.md
        - 庄凌浩(PUMC): experiences/2025/庄凌浩.md
    - 系列辅导: 
      - 扬帆起航: series-pilots/main.md
      - senior-1: series-pilots/senior-1.md
      - senior-2: series-pilots/senior-2.md
      - senior-3: series-pilots/senior-3.md
    - 告示栏: advertise.md
    - 贡献指南: contribute.md
    - 讨论区: issue.md

